// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@redistribux.com",
                            Name = "Super Admin",
                            PasswordHash = "hashed_password_here"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedLocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DemandMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CalendarEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            AffectedLocationType = "All",
                            DemandMultiplier = 3.5m,
                            EndDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "Promotion",
                            Name = "Black Friday",
                            StartDate = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.DailySale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("DailySales", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchasingPower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "Stand Iulius Mall",
                            Profile = "Mixed",
                            PurchasingPower = "Premium"
                        },
                        new
                        {
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Stand Universitate",
                            Profile = "University",
                            PurchasingPower = "Budget"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PhoneModel", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LifeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ModelId");

                    b.ToTable("PhoneModels", (string)null);

                    b.HasData(
                        new
                        {
                            ModelId = new Guid("44444444-4444-4444-4444-444444444441"),
                            LifeStatus = "New",
                            ModelName = "iPhone 15 Pro",
                            ReleaseDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ModelId = new Guid("44444444-4444-4444-4444-444444444442"),
                            LifeStatus = "Declining",
                            ModelName = "Samsung Galaxy S22",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PhoneModelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("PhoneModelId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("55555555-5555-5555-5555-555555555551"),
                            Category = "Case",
                            Name = "Husa Silicon iPhone 15 Pro",
                            PhoneModelId = new Guid("44444444-4444-4444-4444-444444444441"),
                            PurchasePrice = 15.50m,
                            SalePrice = 89.99m,
                            Sku = "IP15P-CASE-BLK"
                        },
                        new
                        {
                            ProductId = new Guid("55555555-5555-5555-5555-555555555552"),
                            Category = "ScreenProtector",
                            Name = "Folie Sticla S22",
                            PhoneModelId = new Guid("44444444-4444-4444-4444-444444444442"),
                            PurchasePrice = 5.00m,
                            SalePrice = 45.00m,
                            Sku = "SGS22-GLASS-01"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StandManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("StandManagers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Email = "ion@stand1.com",
                            LocationId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "Ion Popescu",
                            PasswordHash = "hashed_password_here"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StockVelocity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastInboundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastInventoryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RemainingStockDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesLast100Days")
                        .HasColumnType("integer");

                    b.Property<int>("SalesLast30Days")
                        .HasColumnType("integer");

                    b.Property<string>("StockConfidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockVelocities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CurrentQuantity = 50,
                            LastInboundDate = new DateTime(2026, 2, 27, 7, 22, 57, 114, DateTimeKind.Utc).AddTicks(3979),
                            LastInventoryDate = new DateTime(2026, 3, 3, 7, 22, 57, 114, DateTimeKind.Utc).AddTicks(4042),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222221"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555551"),
                            RemainingStockDays = 12.5m,
                            SalesLast100Days = 350,
                            SalesLast30Days = 120,
                            StockConfidence = "High"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransferBatch", b =>
                {
                    b.Property<Guid>("TransferBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DenialReason")
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LogisticCostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RecommendedBySystemAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSaleValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransferScore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TransferBatchId");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("TransferBatches", (string)null);

                    b.HasData(
                        new
                        {
                            TransferBatchId = new Guid("99999999-9999-9999-9999-999999999991"),
                            DestinationLocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LogisticCostTotal = 25.00m,
                            RecommendedBySystemAt = new DateTime(2026, 3, 4, 5, 22, 57, 114, DateTimeKind.Utc).AddTicks(5807),
                            SourceLocationId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Status = "Proposed",
                            TotalSaleValue = 449.95m,
                            TransferScore = 85.50m
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransferBatchProducts", b =>
                {
                    b.Property<Guid>("TransferBatchProductsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransferBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("TransferBatchProductsId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransferBatchId");

                    b.ToTable("TransferBatchProducts", (string)null);

                    b.HasData(
                        new
                        {
                            TransferBatchProductsId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555551"),
                            Quantity = 10,
                            TransferBatchId = new Guid("99999999-9999-9999-9999-999999999991")
                        },
                        new
                        {
                            TransferBatchProductsId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555552"),
                            Quantity = 5,
                            TransferBatchId = new Guid("99999999-9999-9999-9999-999999999991")
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransportCost", b =>
                {
                    b.Property<Guid>("TransportCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("TransportCostId");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("TransportCosts", (string)null);

                    b.HasData(
                        new
                        {
                            TransportCostId = new Guid("66666666-6666-6666-6666-666666666661"),
                            Cost = 25.00m,
                            DestinationLocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SourceLocationId = new Guid("22222222-2222-2222-2222-222222222221")
                        });
                });

            modelBuilder.Entity("Domain.Entities.DailySale", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.PhoneModel", "PhoneModel")
                        .WithMany()
                        .HasForeignKey("PhoneModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PhoneModel");
                });

            modelBuilder.Entity("Domain.Entities.StandManager", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Entities.StockVelocity", b =>
                {
                    b.HasOne("Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.TransferBatch", b =>
                {
                    b.HasOne("Domain.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("Domain.Entities.TransferBatchProducts", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TransferBatch", "TransferBatch")
                        .WithMany("Products")
                        .HasForeignKey("TransferBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TransferBatch");
                });

            modelBuilder.Entity("Domain.Entities.TransportCost", b =>
                {
                    b.HasOne("Domain.Entities.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("Domain.Entities.TransferBatch", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
