import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import SideMenu from '../components/SideMenu'

function HomePage() {
	const [activePage, setActivePage] = useState('rooms')
	const navigate = useNavigate()

	const handleNavigate = (pageId) => {
		setActivePage(pageId)
		if (pageId === 'profile') {
			//something
		}
	}

	const handleLogout = () => {
		navigate('/auth')
	}

	return (
		<div className="min-h-screen bg-[#f9f6f2] text-[#46190c] flex">
			<SideMenu
				activePage={activePage}
				onNavigate={handleNavigate}
				userName="Alexia"
				onLogout={handleLogout}
			/>

			<div className="flex-1 flex flex-col">
				<main className="px-6 py-8 md:px-10 md:py-10">
					<section className="max-w-5xl mx-auto space-y-6">
						<div className="space-y-2">
							<h1 className="text-3xl font-semibold tracking-tight">Welcome to your redistribution cockpit</h1>
							<p className="text-sm text-[#8a5a43] max-w-xl">
								Here you&apos;ll be able to see products in DEAD_STOCK and STOCKOUT_RISK, recommended transfer
								batches, and how the ML model projects days of stock across all locations.
							</p>
						</div>

						<div className="grid gap-6 md:grid-cols-3">
							<div className="rounded-2xl border border-[#eddccf] bg-white p-4 shadow-sm" id="overview">
								<h2 className="text-sm font-semibold mb-1">Stock overview</h2>
								<p className="text-xs text-[#8a5a43]">
									Coming soon: cards with total DEAD_STOCK units, STOCKOUT_RISK pairs, and normal inventory.
								</p>
							</div>
							<div className="rounded-2xl border border-[#eddccf] bg-white p-4 shadow-sm" id="transfers">
								<h2 className="text-sm font-semibold mb-1">Recommended transfers</h2>
								<p className="text-xs text-[#8a5a43]">
									This area will list the batches generated by the transfer recommendation engine.
								</p>
							</div>
							<div className="rounded-2xl border border-[#eddccf] bg-white p-4 shadow-sm" id="model">
								<h2 className="text-sm font-semibold mb-1">Model insights</h2>
								<p className="text-xs text-[#8a5a43]">
									Later you can surface metrics like average days_of_stock_ml or forecast accuracy here.
								</p>
							</div>
						</div>
					</section>
				</main>
			</div>
		</div>
	)
}

export default HomePage
